services:
  - type: "web_service"
    name: "eau-confessions-bot"
    env: "python"
    pythonVersion: "3.11.4"
    plan: "starter"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: "API_TOKEN"
        value: ""
      - key: "CHANNEL_ID"
        value: ""
      - key: "DB_PATH"
        value: "eaubot.db"
      - key: "WEBHOOK_HOST"
        value: ""
